package Views;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JTextArea;
import javax.swing.JTextField;


public class SchedulePanel extends javax.swing.JPanel {
    
    private String subjectName;
    private String professorName;
    private Color background;
    private Color foreground;
    public SchedulePanel(String subjectName, String professorName, Color background, Color foreground) {
        this.subjectName = subjectName;
        this.professorName = professorName;
        this.background = background;
        this.foreground = foreground;
        initComponents();
    }

    public String getSubjectName() {
        return subjectName;
    }

    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
        subjectTextArea.setText(subjectName);
    }

    public String getProfessorName() {
        return professorName;
    }

    public void setProfessorName(String professorName) {
        this.professorName = professorName;
        professorLabel.setText(this.professorName);
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        subjectTextArea = new javax.swing.JTextArea();
        professorLabel = new javax.swing.JLabel();

        jScrollPane2.setViewportView(jEditorPane1);

        setBackground(background);
        setForeground(foreground);
        setPreferredSize(new java.awt.Dimension(55, 100));

        subjectTextArea.setEditable(false);
        subjectTextArea.setBackground(background);
        subjectTextArea.setColumns(20);
        subjectTextArea.setForeground(foreground);
        subjectTextArea.setLineWrap(true);
        subjectTextArea.setRows(5);
        subjectTextArea.setText(subjectName);
        subjectTextArea.setWrapStyleWord(true);

        professorLabel.setBackground(background);
        professorLabel.setForeground(foreground);
        professorLabel.setText(professorName);
        professorLabel.setPreferredSize(new java.awt.Dimension(72, 16));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subjectTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(professorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subjectTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(professorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        subjectTextArea.setAlignmentX(JTextArea.CENTER_ALIGNMENT);
        subjectTextArea.setAlignmentY(JTextArea.CENTER_ALIGNMENT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel professorLabel;
    private javax.swing.JTextArea subjectTextArea;
    // End of variables declaration//GEN-END:variables
}
